spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/book_jeok?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        jdbc:
          core: TRACE
naver:
  search:
    id: 6TsQArFK66LkJiytgMK2
    secret: tnfB6vylIv
auth:
  admin-email: ${ADMIN_EMAIL}
jwt:
  secret-key: ${SECRET_KEY}
  expiration:
    access-token: 300
    refresh-token: 400

