spring:
  h2:
    console:
      enabled: true
      path: /h2     # (1) Context path
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL   # (2) JDBC URL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        jdbc:
          core: TRACE
naver:
  search:
    id: 6TsQArFK66LkJiytgMK2
    secret: tnfB6vylIv
auth:
  admin-email: ${ADMIN_EMAIL}
jwt:
  secret-key: ${SECRET_KEY}
  expiration:
    access-token: 300
    refresh-token: 400

