spring:
  h2:
    console:
      enabled: true
      path: /h2     # (1) Context path
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL   # (2) JDBC URL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE